### ISSUE TITLE
Missing SQL Parameter

### ISSUE THREAD

**Issue by Medisex64** [AddictedCS/soundfingerprinting.sql#1]
When I try to test the app using MS SQL persistent storage I get the following error.
Procedure or function 'sp_InsertTrack' expects parameter '@TrackLengthSec', which was not supplied.

**Comment by AddictedCS** [comment]
Which version of the library are you using?

**Comment by Medisex64** [comment]
Both are the latest version, namely SoundFingerprinting relesae 3.0.x and SoundFingerprinting.SQL 3.0.0. I have hardcoded a `@TrackLength` for all tracks to be added into the database. I tried removing the parameter from SQL server just to give it a try, after removing that one, it complains about `@GroupId` parameter missing, after removing that one too the error becomes 

> Procedure or function sp_InsertTrack has too many arguments specified.

**Comment by AddictedCS** [comment]
It seems that you've initialized the database with out-dated script. With 3.0.0 there is no more `TrackLength` nor `GroupId` parameters in any of the stored procedures. https://github.com/AddictedCS/soundfingerprinting.sql/blob/release/3.0.x/src/Scripts/DBScript.sql

**Comment by ghost** [comment]
Now works like a charm. Yet I don't know how to setup `Solr` storage, there is no help for seting it up, like which storage model to use and how to connect to the storage.

**Comment by AddictedCS** [comment]
Solr repository is located here: https://github.com/AddictedCS/soundfingerprinting.solr. You can try it in docker or set it up manually.
